### ISSUE TITLE
Auto tag complete not working on Linux (Mint)

### ISSUE THREAD

**Issue by divs1210** [LightTable/HTML#5]
HTML tags aren't closing automatically. Do I have to make some changes for that?

**Comment by rundis** [comment]
Are you using the latest version of the html plugin ? (0.1.0) 

- ctrl+space
- `show plugin manager`
- locate the html plugin
- if it says 0.0.2 there should be an update button there (if not close the plugin manager and reopen).
- click update

tried on ubuntu 14 

cheers
Magnus

**Comment by divs1210** [comment]
Hey! 
I have the latest version of both LT and the plugin. 
I'm using Mint 17.1.

**Comment by cldwalker** [comment]
@divs1210 It seems you're asking for two things: autocompletion and autoclosing. The HTML plugin doesn't have autocompletion of html tags. It does have autoclosing of tags ([CodeMirror demo](https://codemirror.net/demo/closetag.html)). If you type `<div>`, a closing `</div>` appears. Are you still interested in autocompletion or should I close this?

**Comment by divs1210** [comment]
No, sorry if I was unclear. I'm not asking for autocomplete, but for autoclosing.
The tags aren't autoclosing. If I type `<p>` nothing happens. I have to type `</p>` myself.

Thanks!

**Comment by kenny-evitt** [comment]
@divs1210 Were you able to get auto-closing to work somehow?

**Comment by divs1210** [comment]
Updating LT didn't solve my problem, so I removed it and downloaded the latest version. Now it works fine. Don't know what was wrong. Thanks for the plugin!

**Comment by cldwalker** [comment]
Fwiw, this feature requires LT 0.8.0-alpha  which you probably didn't have initially
